### ISSUE TITLE
typo in the vignette

### ISSUE THREAD

**Issue by statadvice** [bradleyboehmke/completejourney#17]
The vignette says:
"Display location (0-display, 1-store front, 2-store rear, 3-front end cap, 4-mid-aisle end cap, 5-rear end cap, 6-side aisle end cap, 7-in-aisle, 9-secondary location display, A-in-shelf)"

Probably, "0-display" should be "0- no display"

**Comment by bradleyboehmke** [comment]
Thanks @statadvice . This has been resolved in our online documentation and in the development version of the package.
