### ISSUE TITLE
link at bottom of README gives 404

### ISSUE THREAD

**Issue by bfgray3** [bradleyboehmke/completejourney#5]

**Comment by bradleyboehmke** [comment]
Yeah, 84.51° recently updated their website.  Consequently, the Area 51 webpage was taken down temporarily but should be back up soon (or it possibly is back up but with a different URL).  I'm checking on an update and can then update the URL if necessary.

**Comment by jeffboichuk** [comment]
The website is back up (see [here](https://www.8451.com/area51)). Closes #5.
