### ISSUE TITLE
UPC values seem infinitesmal

### ISSUE THREAD

**Issue by bradleyboehmke** [bradleyboehmke/completejourney#6]
Need to validate the UPC values so we can make sure coupons and coupon_redemption tables can be accurately joined.

@StevenMMortimer can you compare the data that you guys originally received to the following lines?  Notice the value of `coupon_upc` (0.xxxxxx e-313)

```
library(dplyr)
coupons %>% 
    filter(campaign == 22) %>%
    distinct(coupon_upc)
      coupon_upc
1  2.574082e-313
2  2.687718e-313
3  2.722306e-313
4  4.940699e-314
5  4.940701e-314
6  4.940699e-314
7  2.855577e-313
8  2.541970e-313
9  2.608668e-313
10 2.709951e-313
11 2.559260e-313
12 2.535150e-313
13 2.690187e-313
14 2.818445e-313
15 2.821153e-313
16 2.674487e-313
17 2.605340e-313
18 2.574729e-313
19 2.778321e-313
20 2.724776e-313
21 2.724776e-313
```

**Comment by StevenMMortimer** [comment]
Looking at the CSV files we downloaded, the values of the `COUPON_UPC` column inside the `coupon_redempt` CSV are all 11-digit numbers starting with a `1` or a `5`. The same goes for the `coupon` CSV.  In our version of the package, we converted them to tibbles, but that shouldn't make a difference. Here is a snippet: 

```
coupon %>% 
    filter(campaign == 22) %>% 
    distinct(coupon_upc)

# A tibble: 21 x 1
    coupon_upc
         <dbl>
 1 52100000031
 2 54400021032
 3 55100090033
 4 10000085486
 5 10000089316
 6 10000085487
 7 57797520075
 8 51450050050
 9 52800031032
10 54850010033
# ... with 11 more rows
```

**Comment by bradleyboehmke** [comment]
Ok, I was able to track down the "translation" problem and got the proper 11-digits.  I'll update the data sets to make sure they are consistent and then close this out.

**Comment by jeffboichuk** [comment]
Sounds great, @bradleyboehmke – thanks!

Should we convert the id variables (e.g., `household_id`, `product_id`, `coupon_id`) into factor variables rather than numeric variables (either integer or double)?

**Comment by bradleyboehmke** [comment]
I'm going to close this out.  The reformatting I did (which uses most of what @StevenMMortimer did in your private repo will be discussed in issue #7
