### ISSUE TITLE
Collapse time columns into a single datetime variable

### ISSUE THREAD

**Issue by StevenMMortimer** [bradleyboehmke/completejourney#8]
The current dataset has a collection of variables like `day`, `week_no`, `trans_time` to indicate the date and time of a transaction, campaign or other entity. We would like to create date and datetime variables wherever possible and index them to a fictitious starting date, such as Jan. 1, 2016.

One oddity in the dataset is that the total sales volume starts at zero and slowly creeps up over the first 100 days. 

![image](https://user-images.githubusercontent.com/5299737/48240811-377dd280-e3a2-11e8-83bb-cd07bcba9604.png)

```
library(tidyverse)
library(completejourney)
transactions %>% 
    group_by(day) %>% 
    summarize(total_sales_value = sum(sales_value, na.rm = TRUE)) %>%
    ggplot() + 
    geom_line(mapping = aes(x = day, y = total_sales_value))
```

It might make sense to cut down the dataset to just one single year of consistent transaction data. This would get rid of the weird sales volume behavior and reduce the total size of the package.

**Comment by bradleyboehmke** [comment]
This was completed with commit [a26f157](https://github.com/bradleyboehmke/completejourney/commit/a26f1578c7c2ad69e3198b9b86f922f1019759a5).  This includes consolidating the date-time stamps and reducing the data down to only 2017.
